[bans]
# multiple-versions = "deny" # FIXME

[sources]
unknown-registry = "deny"
unknown-git      = "deny"
allow-git = [
    "https://github.com/duesee/smtp-codec",
    "https://github.com/duesee/pop3-codec",
    "https://github.com/duesee/imap-codec",
]

[licenses]
allow = [ "Apache-2.0", "MIT", "0BSD" ]
