[advisories]
ignore = [
    "RUSTSEC-2020-0159", # :-(
]

[bans]
# multiple-versions = "deny" # FIXME

[sources]
unknown-registry = "deny"
unknown-git      = "deny"
allow-git = [
    "https://github.com/duesee/smtp-codec",
    "https://github.com/duesee/pop3-codec",
    "https://github.com/duesee/imap-codec",
]

[licenses]
allow = [ "Apache-2.0", "MIT", "0BSD", "BSD-3-Clause" ]

# FIXME, because ...
unlicensed = "warn"

# ... I can't get this to work ...
#[[licenses.clarify]]
#name = "encoding_rs"
#expression = "MIT OR Apache-2.0"
#license-files = [
#    { path = "LICENSE-MIT", hash = 0xbd0eed23 },
#    { path = "LICENSE-APACHE", hash = 0xbd0eed23 },
#]
